### ISSUE TITLE
Abuse on Expirebox

### ISSUE THREAD

**Issue by rcpmedia** [mastercs999/keylogger#8]
I have just submitted an abuse complaint on GitHub
Delete this keylogger or delete Expirebox.com from the script, you are not authorized for this use, we went back to you after some investigations for continuous and repeated attacks on our server by thousands of files sent by your script.
You are not authorized to circumvent the site's upload system, this is theft of resources.

**Comment by mastercs999** [comment]
Is this behavior described as forbidden somewhere in TOS?

**Comment by rcpmedia** [comment]
Are you kidding? I am the owner of the server from which you are stealing resources by hacking my website and you want it written in TOS that is prohibited? are you forcibly bypassing the upload system, where did you read that you could do it?
How much are you 10 years old? 

I can also go to the post police tomorrow, This attack can compromise my work, it's business is not a game.



Da: mastercs999
Inviato: domenica 16 settembre 2018 11:17
A: mastercs999/keylogger
Cc: WebSyrup; Author
Oggetto: Re: [mastercs999/keylogger] Abuse on Expirebox (#8)

Is this behavior described as forbidden somewhere in TOS?
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.



---
Questa e-mail è stata controllata per individuare virus con Avast antivirus.
https://www.avast.com/antivirus

**Comment by mastercs999** [comment]
Please contact me on kygo.unlimited@gmail.com from your ExpireBox email. We'll find a way.

**Comment by rcpmedia** [comment]
Yes I contact you Tomorrow, but, the way is that you behave like a correct and serious person and delete expirebox from your script, there are other services that give free APIs.




Da: mastercs999
Inviato: domenica 16 settembre 2018 23:35
A: mastercs999/keylogger
Cc: WebSyrup; Author
Oggetto: Re: [mastercs999/keylogger] Abuse on Expirebox (#8)

Please contact me on kygo.unlimited@gmail.com from your ExpireBox email. We'll find a way.
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.



---
Questa e-mail è stata controllata per individuare virus con Avast antivirus.
https://www.avast.com/antivirus

**Comment by mastercs999** [comment]
OK. Waiting for the email. Thanks.

**Comment by mastercs999** [comment]
No email received. Couldn't verify identity.
